Admin.create(name: "Admin User", password:"password", email: "admin@admin.com", business_id: 1)
Client.create(name:  "Client User", password: "password", email: "client@client.com", phone: "5127889900", business_id: 1)
Client.create(name:  "Mrs Clean", password: "password", email: "client2@client2.com", phone: "4993333333", business_id: 1)
Client.create(name:  "Mrs Dirty", password: "password", email: "client3@client3.com", phone: "4993333333", business_id: 1)
Shipper.create(name: "john", email: "shipper@shipper.com", password: "password",  phone: "5122223344", business_id: 1)
Shipper.create(name: "jeff", email: "shipper2@shipper2.com", password: "password",  phone: "5122211111", business_id: 1)
Business.create(name: 'Wash', email: 'wash@wash.com', hash_password: 'password')
Order.create(box_in: 1, client_id: 1, business_id: 1, status: 'Incomming', total: 100, paid: false)
Order.create(box_in: 1, client_id: 2, business_id: 1, status: 'In Box', total: 100, paid: false)
Order.create(box_in: 1, client_id: 3, business_id: 1, status: 'Incomming', total: 100, paid: false)